### ISSUE TITLE
Serait-il possible que l'algo choisisse un paragraphe entier de texte plutôt qu'une seule ligne? 

### ISSUE THREAD

**Issue by trivoallan** [constructions-incongrues/lesbarques#3]
Serait-il possible que l'algo choisisse un paragraphe entier de texte plutôt qu'une seule ligne? Ou que j'inscrive des balises dans le code de la page source pour mieux cibler les extraits?

**Comment by trivoallan** [comment]
@UolpUb vu que github a l'air de t'intéresser, essayons de l'utiliser pour causer :)

Deux solutions s'offrent à nous :
- Le ciblage des textes via une balise dédiée. C'est précis, mais fastidieux (pour toi).
- La définition d'un nombre de caractères minimum pour qu'un texte soit éligible. C'est fastoche ;) Il suffit que tu me donnes la valeur du seuil

Dis-moi quelle solution tu choisis.

**Comment by UolpUb** [comment]
à mon avis, à terme il faudra de toutes façons que je fasse une sélection précise des textes, donc cette histoire de balise risque de se révéler obligatoire.
Mais peut-être qu'en attendant on peut tenter le nombre de caractère minimum, juste pour se faire une idée. Partons sur 1500 caractère par exemple, pour voir...

**Comment by UolpUb** [comment]
ça fonctionne déjà beaucoup mieux! Mais est-ce qu'il serait aussi possible d'ajouter un "always fit" pour le texte? en l'occurence les 1500 caractères passent très bien avec la résolution de mon ordinateur, mais sur l'écran de mon téléphone ils débordent de l'image et vont se perdre loin en dessous

**Comment by trivoallan** [comment]
@UolpUb  En attendant une validation plus ciblée, j'ai défini un interval éligible entre 200 et 400 caractères.

Tu peux changer les valeurs à cette adresse : https://github.com/constructions-incongrues/lesbarques/settings/variables/actions

Une fois les variables modidiées, il faut regénérer un nouveau site. Tu peux faire ça là : https://github.com/constructions-incongrues/lesbarques/actions/workflows/build.yml (bouton "run workflow").

**Comment by trivoallan** [comment]
> ça fonctionne déjà beaucoup mieux! Mais est-ce qu'il serait aussi possible d'ajouter un "always fit" pour le texte? en l'occurence les 1500 caractères passent très bien avec la résolution de mon ordinateur, mais sur l'écran de mon téléphone ils débordent de l'image et vont se perdre loin en dessous

Ça n'est pas possible car le texte qui va illustrer le site est choisi bien avant qu'on sache quel périphérique va afficher le site.

**Comment by UolpUb** [comment]
ça fonctionne bien avec cette nouvelle présentation. Pourrais-tu me montrer à quelle endroit du code je peux changer la taille du texte et la transparence du cadre? ça me permettrait d'être autonome pour faire des petits tests. M'ci!

**Comment by trivoallan** [comment]
Hello tout est là : https://github.com/constructions-incongrues/lesbarques/blob/main/templates/index.html

ATTATION : Les modifications ne sont visibles qu'après exécution d'un https://github.com/constructions-incongrues/lesbarques/actions/workflows/build.yml

**Comment by UolpUb** [comment]
Merci! Je me suis déjà permis de bidouiller un peu sans demander... pardon... mais c'est agréable, je comprends quelques trucs..

**Comment by UolpUb** [comment]
Mais j’ai gardé de côté bien au chaud la partie du code qui permettrait de remettre le texte, bien sûr:)
