### ISSUE TITLE
Ah et le projet s'appellera 'Les barques'

### ISSUE THREAD

**Issue by trivoallan** [constructions-incongrues/lesbarques#6]

**Comment by trivoallan** [comment]
@UolpUb c'est juste "Les Barques" ou bien "Les Barques - Loup Uberto" ?

**Comment by trivoallan** [comment]
J'ai renommé le dépôt en conséquence : https://github.com/constructions-incongrues/lesbarques

**Comment by UolpUb** [comment]
Juste "Les Barques" c'est parfait, merci!
